### ISSUE TITLE
Region Interactions

### ISSUE THREAD

**Issue by lordsoffallen** [instantX-research/Regional-Prompting-FLUX#11]
When two regions need to interact with each other, how should that appear in the regional prompts? For instance I wanna have a scene where one guy sits at a bar and another guy claps him shoulder. This scene requires second region (the other guy) interacting with the first region. Following this, i wonder if the regions could overlap somehow? Or do they have to be distinctly separate?

**Comment by antonioo-c** [comment]
@lordsoffallen It's better that the regions are distinct; otherwise, the multiple objects might blend into one object. The regional boxes aren't that strictly controlling the image, if you lower the control strength. Then, in this case, people in the image can reach their hands out of the regional box, thus achieving interaction.
